### ISSUE TITLE
社会社会

### ISSUE THREAD

**Issue by LeungYu** [OneSecure/ShadowAgentNotes#1]
听说大佬被请喝茶过，还是建议做这一类产品之前先肉身翻墙，至少不会被逮住

**Comment by OneSecure** [comment]
中共打击这方面的人首先考虑的是它们肉眼可见的盈利行为如卖VPN，非法经营罪就扣头上了，判个三年五年。我免费教唆翻墙它们能咋的？最多喝茶，吓唬吓唬。我知道流氓政权的行事逻辑。

**Comment by LeungYu** [comment]
就算没有盈利还能扣一个破坏计算机信息系统罪，所以吧，还是肉身翻墙最稳妥，就算被国内机关叫去喝茶也可以不去，反正引渡不回去
